name: CI

on: [push]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get composer cache dir
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer downloads
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{hash_files('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.os }}-build-${{hash_files('**/composer.lock') }}
      - uses: php-actions/composer@v2
      - uses: php-actions/phpstan@v1
        with:
          configuration: phpstan.neon
      - uses: php-actions/phpunit@v9
        with:
          args: tests
